# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addDesignRowDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(262, 204)
        Dialog.setMinimumSize(QtCore.QSize(262, 204))
        Dialog.setMaximumSize(QtCore.QSize(262, 204))
        Dialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.spinBox_deep = QtWidgets.QSpinBox(Dialog)
        self.spinBox_deep.setMaximum(999999999)
        self.spinBox_deep.setSingleStep(6)
        self.spinBox_deep.setObjectName("spinBox_deep")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_deep)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.doubleSpinBox_designAngle = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_designAngle.setMinimum(-30.0)
        self.doubleSpinBox_designAngle.setMaximum(30.0)
        self.doubleSpinBox_designAngle.setObjectName("doubleSpinBox_designAngle")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_designAngle)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.doubleSpinBox_designDirction = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_designDirction.setMaximum(360.0)
        self.doubleSpinBox_designDirction.setObjectName("doubleSpinBox_designDirction")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_designDirction)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.spinBox_top = QtWidgets.QSpinBox(Dialog)
        self.spinBox_top.setMinimum(-300)
        self.spinBox_top.setMaximum(300)
        self.spinBox_top.setSingleStep(6)
        self.spinBox_top.setObjectName("spinBox_top")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBox_top)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.spinBox_bottom = QtWidgets.QSpinBox(Dialog)
        self.spinBox_bottom.setMinimum(-300)
        self.spinBox_bottom.setMaximum(300)
        self.spinBox_bottom.setSingleStep(6)
        self.spinBox_bottom.setObjectName("spinBox_bottom")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinBox_bottom)
        self.verticalLayout.addLayout(self.formLayout)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_OK = QtWidgets.QPushButton(Dialog)
        self.pushButton_OK.setObjectName("pushButton_OK")
        self.horizontalLayout.addWidget(self.pushButton_OK)
        self.pushButton_Cancel = QtWidgets.QPushButton(Dialog)
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.horizontalLayout.addWidget(self.pushButton_Cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "孔深："))
        self.spinBox_deep.setSuffix(_translate("Dialog", "m"))
        self.label_2.setText(_translate("Dialog", "设计倾角："))
        self.doubleSpinBox_designAngle.setSuffix(_translate("Dialog", "°"))
        self.label_3.setText(_translate("Dialog", "设计方位："))
        self.doubleSpinBox_designDirction.setSuffix(_translate("Dialog", "°"))
        self.label_4.setText(_translate("Dialog", "顶板相对标高："))
        self.spinBox_top.setSuffix(_translate("Dialog", "m"))
        self.label_5.setText(_translate("Dialog", "底板相对标高："))
        self.spinBox_bottom.setSuffix(_translate("Dialog", "m"))
        self.pushButton_OK.setText(_translate("Dialog", "确定"))
        self.pushButton_Cancel.setText(_translate("Dialog", "取消"))

