# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindows.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1209, 808)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_image = QtWidgets.QWidget()
        self.tab_image.setObjectName("tab_image")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_image)
        self.gridLayout.setObjectName("gridLayout")
        self.threeDwidget = myGLWidget_withGride(self.tab_image)
        self.threeDwidget.setMinimumSize(QtCore.QSize(500, 400))
        self.threeDwidget.setObjectName("threeDwidget")
        self.gridLayout.addWidget(self.threeDwidget, 0, 0, 1, 1)
        self.widget_y = myPlotWidget_y(self.tab_image)
        self.widget_y.setMinimumSize(QtCore.QSize(250, 0))
        self.widget_y.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widget_y.setObjectName("widget_y")
        self.gridLayout.addWidget(self.widget_y, 0, 1, 1, 1)
        self.widget_x = myPlotWidget_x(self.tab_image)
        self.widget_x.setMinimumSize(QtCore.QSize(0, 200))
        self.widget_x.setMaximumSize(QtCore.QSize(16777215, 300))
        self.widget_x.setObjectName("widget_x")
        self.gridLayout.addWidget(self.widget_x, 1, 0, 1, 1)
        self.widget_z = myPlotWidget_z(self.tab_image)
        self.widget_z.setMinimumSize(QtCore.QSize(250, 200))
        self.widget_z.setMaximumSize(QtCore.QSize(300, 300))
        self.widget_z.setObjectName("widget_z")
        self.gridLayout.addWidget(self.widget_z, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_image, "")
        self.tab_tabel = QtWidgets.QWidget()
        self.tab_tabel.setObjectName("tab_tabel")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_tabel)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableView = QtWidgets.QTableView(self.tab_tabel)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_3.addWidget(self.tableView)
        self.tabWidget.addTab(self.tab_tabel, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1209, 26))
        self.menubar.setObjectName("menubar")
        self.menu3D = QtWidgets.QMenu(self.menubar)
        self.menu3D.setObjectName("menu3D")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_trackTree = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_trackTree.setObjectName("dockWidget_trackTree")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dockWidgetContents_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treeWidget = trackTree(self.dockWidgetContents_2)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "track tree")
        self.horizontalLayout.addWidget(self.treeWidget)
        self.dockWidget_trackTree.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_trackTree)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWidget_toolBox = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_toolBox.setMinimumSize(QtCore.QSize(300, 193))
        self.dockWidget_toolBox.setMaximumSize(QtCore.QSize(350, 300))
        self.dockWidget_toolBox.setObjectName("dockWidget_toolBox")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolBox = QtWidgets.QToolBox(self.dockWidgetContents)
        self.toolBox.setObjectName("toolBox")
        self.page_track = QtWidgets.QWidget()
        self.page_track.setGeometry(QtCore.QRect(0, 0, 282, 417))
        self.page_track.setObjectName("page_track")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_track)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.page_track)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.line = QtWidgets.QFrame(self.page_track)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_5.addWidget(self.line)
        self.label_currentTrack = QtWidgets.QLabel(self.page_track)
        self.label_currentTrack.setObjectName("label_currentTrack")
        self.verticalLayout_5.addWidget(self.label_currentTrack)
        self.checkBox_showDesignTrack = QtWidgets.QCheckBox(self.page_track)
        self.checkBox_showDesignTrack.setObjectName("checkBox_showDesignTrack")
        self.verticalLayout_5.addWidget(self.checkBox_showDesignTrack)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.groupBox = QtWidgets.QGroupBox(self.page_track)
        self.groupBox.setMinimumSize(QtCore.QSize(100, 100))
        self.groupBox.setMaximumSize(QtCore.QSize(200, 120))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.radioButton_showOne = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_showOne.setObjectName("radioButton_showOne")
        self.verticalLayout_4.addWidget(self.radioButton_showOne)
        self.radioButton_showAll = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_showAll.setObjectName("radioButton_showAll")
        self.verticalLayout_4.addWidget(self.radioButton_showAll)
        self.radioButton_showMutliple = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_showMutliple.setEnabled(True)
        self.radioButton_showMutliple.setChecked(True)
        self.radioButton_showMutliple.setObjectName("radioButton_showMutliple")
        self.verticalLayout_4.addWidget(self.radioButton_showMutliple)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.page_track)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.checkBox_referenceX = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_referenceX.setChecked(True)
        self.checkBox_referenceX.setObjectName("checkBox_referenceX")
        self.horizontalLayout_8.addWidget(self.checkBox_referenceX)
        self.horizontalSlider_referenceX = QtWidgets.QSlider(self.groupBox_4)
        self.horizontalSlider_referenceX.setMaximum(10)
        self.horizontalSlider_referenceX.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_referenceX.setObjectName("horizontalSlider_referenceX")
        self.horizontalLayout_8.addWidget(self.horizontalSlider_referenceX)
        self.doubleSpinBox_referenceX = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBox_referenceX.setMaximum(10.0)
        self.doubleSpinBox_referenceX.setObjectName("doubleSpinBox_referenceX")
        self.horizontalLayout_8.addWidget(self.doubleSpinBox_referenceX)
        self.verticalLayout_11.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.checkBox_referenceY = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_referenceY.setChecked(True)
        self.checkBox_referenceY.setObjectName("checkBox_referenceY")
        self.horizontalLayout_9.addWidget(self.checkBox_referenceY)
        self.horizontalSlider_referenceY = QtWidgets.QSlider(self.groupBox_4)
        self.horizontalSlider_referenceY.setMaximum(10)
        self.horizontalSlider_referenceY.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_referenceY.setObjectName("horizontalSlider_referenceY")
        self.horizontalLayout_9.addWidget(self.horizontalSlider_referenceY)
        self.doubleSpinBox_referenceY = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBox_referenceY.setMaximum(10.0)
        self.doubleSpinBox_referenceY.setObjectName("doubleSpinBox_referenceY")
        self.horizontalLayout_9.addWidget(self.doubleSpinBox_referenceY)
        self.verticalLayout_11.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.checkBox_referenceZ = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_referenceZ.setChecked(True)
        self.checkBox_referenceZ.setObjectName("checkBox_referenceZ")
        self.horizontalLayout_10.addWidget(self.checkBox_referenceZ)
        self.horizontalSlider_referenceZ = QtWidgets.QSlider(self.groupBox_4)
        self.horizontalSlider_referenceZ.setMaximum(10)
        self.horizontalSlider_referenceZ.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_referenceZ.setObjectName("horizontalSlider_referenceZ")
        self.horizontalLayout_10.addWidget(self.horizontalSlider_referenceZ)
        self.doubleSpinBox_referenceZ = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBox_referenceZ.setMaximum(10.0)
        self.doubleSpinBox_referenceZ.setObjectName("doubleSpinBox_referenceZ")
        self.horizontalLayout_10.addWidget(self.doubleSpinBox_referenceZ)
        self.verticalLayout_11.addLayout(self.horizontalLayout_10)
        self.verticalLayout_6.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.page_track)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_4.addWidget(self.checkBox_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_13.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.checkBox_referenceX_3 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_referenceX_3.setChecked(False)
        self.checkBox_referenceX_3.setObjectName("checkBox_referenceX_3")
        self.horizontalLayout_14.addWidget(self.checkBox_referenceX_3)
        self.horizontalSlider_referenceX_3 = QtWidgets.QSlider(self.groupBox_5)
        self.horizontalSlider_referenceX_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_referenceX_3.setObjectName("horizontalSlider_referenceX_3")
        self.horizontalLayout_14.addWidget(self.horizontalSlider_referenceX_3)
        self.spinBox_4 = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinBox_4.setObjectName("spinBox_4")
        self.horizontalLayout_14.addWidget(self.spinBox_4)
        self.verticalLayout_13.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.checkBox_referenceY_3 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_referenceY_3.setChecked(False)
        self.checkBox_referenceY_3.setObjectName("checkBox_referenceY_3")
        self.horizontalLayout_15.addWidget(self.checkBox_referenceY_3)
        self.horizontalSlider_referenceY_3 = QtWidgets.QSlider(self.groupBox_5)
        self.horizontalSlider_referenceY_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_referenceY_3.setObjectName("horizontalSlider_referenceY_3")
        self.horizontalLayout_15.addWidget(self.horizontalSlider_referenceY_3)
        self.spinBox_5 = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinBox_5.setObjectName("spinBox_5")
        self.horizontalLayout_15.addWidget(self.spinBox_5)
        self.verticalLayout_13.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.checkBox_referenceZ_3 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_referenceZ_3.setChecked(False)
        self.checkBox_referenceZ_3.setObjectName("checkBox_referenceZ_3")
        self.horizontalLayout_16.addWidget(self.checkBox_referenceZ_3)
        self.horizontalSlider_referenceZ_3 = QtWidgets.QSlider(self.groupBox_5)
        self.horizontalSlider_referenceZ_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_referenceZ_3.setObjectName("horizontalSlider_referenceZ_3")
        self.horizontalLayout_16.addWidget(self.horizontalSlider_referenceZ_3)
        self.spinBox_6 = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinBox_6.setObjectName("spinBox_6")
        self.horizontalLayout_16.addWidget(self.spinBox_6)
        self.verticalLayout_13.addLayout(self.horizontalLayout_16)
        self.verticalLayout_6.addWidget(self.groupBox_5)
        self.toolBox.addItem(self.page_track, "")
        self.page_image = QtWidgets.QWidget()
        self.page_image.setGeometry(QtCore.QRect(0, 0, 278, 190))
        self.page_image.setObjectName("page_image")
        self.toolBox.addItem(self.page_image, "")
        self.verticalLayout.addWidget(self.toolBox)
        self.dockWidget_toolBox.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_toolBox)
        self.action_menu_openProjiect = QtWidgets.QAction(MainWindow)
        self.action_menu_openProjiect.setObjectName("action_menu_openProjiect")
        self.action_menu_newProject = QtWidgets.QAction(MainWindow)
        self.action_menu_newProject.setObjectName("action_menu_newProject")
        self.action_menu_recentProject = QtWidgets.QAction(MainWindow)
        self.action_menu_recentProject.setObjectName("action_menu_recentProject")
        self.action_tool_start = QtWidgets.QAction(MainWindow)
        self.action_tool_start.setObjectName("action_tool_start")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.action_tool_chooseMainTrack = QtWidgets.QAction(MainWindow)
        self.action_tool_chooseMainTrack.setObjectName("action_tool_chooseMainTrack")
        self.action_tool_linkPort = QtWidgets.QAction(MainWindow)
        self.action_tool_linkPort.setObjectName("action_tool_linkPort")
        self.action_menu_export = QtWidgets.QAction(MainWindow)
        self.action_menu_export.setObjectName("action_menu_export")
        self.action_tool_correctToolFace = QtWidgets.QAction(MainWindow)
        self.action_tool_correctToolFace.setObjectName("action_tool_correctToolFace")
        self.action_tool_changeToolFace = QtWidgets.QAction(MainWindow)
        self.action_tool_changeToolFace.setObjectName("action_tool_changeToolFace")
        self.action_designTrack = QtWidgets.QAction(MainWindow)
        self.action_designTrack.setObjectName("action_designTrack")
        self.menu_2.addAction(self.action_menu_newProject)
        self.menu_2.addAction(self.action_menu_openProjiect)
        self.menu_2.addAction(self.action_menu_recentProject)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.action_menu_export)
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu3D.menuAction())
        self.toolBar.addAction(self.action_tool_chooseMainTrack)
        self.toolBar.addAction(self.action_designTrack)
        self.toolBar.addAction(self.action_tool_linkPort)
        self.toolBar.addAction(self.action_tool_start)
        self.toolBar.addAction(self.action_tool_correctToolFace)
        self.toolBar.addAction(self.action_tool_changeToolFace)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DrillTrack3D"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_image), _translate("MainWindow", "测斜轨迹"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_tabel), _translate("MainWindow", "测斜数据"))
        self.menu3D.setTitle(_translate("MainWindow", "设置"))
        self.menu_2.setTitle(_translate("MainWindow", "文件"))
        self.menu_3.setTitle(_translate("MainWindow", "显示"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.label.setText(_translate("MainWindow", "当前选中的轨迹"))
        self.label_currentTrack.setText(_translate("MainWindow", "未选中"))
        self.checkBox_showDesignTrack.setText(_translate("MainWindow", "显示设计轨迹"))
        self.groupBox.setTitle(_translate("MainWindow", "显示策略"))
        self.radioButton_showOne.setText(_translate("MainWindow", "显示单条轨迹"))
        self.radioButton_showAll.setText(_translate("MainWindow", "显示多条轨迹"))
        self.radioButton_showMutliple.setText(_translate("MainWindow", "显示所有分支"))
        self.groupBox_4.setTitle(_translate("MainWindow", "参考线/网面"))
        self.checkBox_referenceX.setText(_translate("MainWindow", "水平参考"))
        self.checkBox_referenceY.setText(_translate("MainWindow", "垂直参考"))
        self.checkBox_referenceZ.setText(_translate("MainWindow", "深度参考"))
        self.groupBox_5.setTitle(_translate("MainWindow", "网面自动刻度"))
        self.checkBox_2.setText(_translate("MainWindow", "不显示刻度"))
        self.checkBox_referenceX_3.setText(_translate("MainWindow", "水平刻度"))
        self.checkBox_referenceY_3.setText(_translate("MainWindow", "垂直参考"))
        self.checkBox_referenceZ_3.setText(_translate("MainWindow", "深度参考"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_track), _translate("MainWindow", "分支孔策略"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_image), _translate("MainWindow", "图像显示策略"))
        self.action_menu_openProjiect.setText(_translate("MainWindow", "打开钻场"))
        self.action_menu_openProjiect.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.action_menu_newProject.setText(_translate("MainWindow", "新建钻场"))
        self.action_menu_newProject.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.action_menu_recentProject.setText(_translate("MainWindow", "最近打开的钻场"))
        self.action_tool_start.setText(_translate("MainWindow", "开始测量"))
        self.action_tool_start.setShortcut(_translate("MainWindow", "Ctrl+Alt+S"))
        self.action_6.setText(_translate("MainWindow", "停止测量"))
        self.action_tool_chooseMainTrack.setText(_translate("MainWindow", "选择主孔"))
        self.action_tool_chooseMainTrack.setShortcut(_translate("MainWindow", "Ctrl+Alt+C"))
        self.action_tool_linkPort.setText(_translate("MainWindow", "端口连接"))
        self.action_tool_linkPort.setShortcut(_translate("MainWindow", "Ctrl+Alt+P"))
        self.action_menu_export.setText(_translate("MainWindow", "导出"))
        self.action_menu_export.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.action_tool_correctToolFace.setText(_translate("MainWindow", "修正工具面"))
        self.action_tool_changeToolFace.setText(_translate("MainWindow", "调整工具面"))
        self.action_designTrack.setText(_translate("MainWindow", "设计轨迹"))

from myWidget import myGLWidget_withGride, myPlotWidget_x, myPlotWidget_y, myPlotWidget_z, trackTree
