# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindows.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1209, 808)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_image = QtWidgets.QWidget()
        self.tab_image.setObjectName("tab_image")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_image)
        self.gridLayout.setObjectName("gridLayout")
        self.threeDwidget = myGLWidget_withGride(self.tab_image)
        self.threeDwidget.setMinimumSize(QtCore.QSize(500, 400))
        self.threeDwidget.setObjectName("threeDwidget")
        self.gridLayout.addWidget(self.threeDwidget, 0, 0, 1, 1)
        self.widget_y = myPlotWidget_y(self.tab_image)
        self.widget_y.setMinimumSize(QtCore.QSize(250, 0))
        self.widget_y.setMaximumSize(QtCore.QSize(250, 16777215))
        self.widget_y.setObjectName("widget_y")
        self.gridLayout.addWidget(self.widget_y, 0, 1, 1, 1)
        self.widget_x = myPlotWidget_x(self.tab_image)
        self.widget_x.setMinimumSize(QtCore.QSize(0, 200))
        self.widget_x.setMaximumSize(QtCore.QSize(16777215, 200))
        self.widget_x.setObjectName("widget_x")
        self.gridLayout.addWidget(self.widget_x, 1, 0, 1, 1)
        self.widget_pos = QtWidgets.QWidget(self.tab_image)
        self.widget_pos.setObjectName("widget_pos")
        self.gridLayout.addWidget(self.widget_pos, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_image, "")
        self.tab_tabel = QtWidgets.QWidget()
        self.tab_tabel.setObjectName("tab_tabel")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_tabel)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_tabel)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.tabWidget.addTab(self.tab_tabel, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1209, 26))
        self.menubar.setObjectName("menubar")
        self.menu3D = QtWidgets.QMenu(self.menubar)
        self.menu3D.setObjectName("menu3D")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_trackTree = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_trackTree.setObjectName("dockWidget_trackTree")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dockWidgetContents_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treeWidget = trackTree(self.dockWidgetContents_2)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "track tree")
        self.horizontalLayout.addWidget(self.treeWidget)
        self.dockWidget_trackTree.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_trackTree)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWidget_toolBox = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_toolBox.setObjectName("dockWidget_toolBox")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolBox = QtWidgets.QToolBox(self.dockWidgetContents)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 256, 216))
        self.page.setObjectName("page")
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 256, 216))
        self.page_2.setObjectName("page_2")
        self.toolBox.addItem(self.page_2, "")
        self.verticalLayout.addWidget(self.toolBox)
        self.dockWidget_toolBox.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_toolBox)
        self.action_menu_openProjiect = QtWidgets.QAction(MainWindow)
        self.action_menu_openProjiect.setObjectName("action_menu_openProjiect")
        self.action_menu_newProject = QtWidgets.QAction(MainWindow)
        self.action_menu_newProject.setObjectName("action_menu_newProject")
        self.action_menu_recentProject = QtWidgets.QAction(MainWindow)
        self.action_menu_recentProject.setObjectName("action_menu_recentProject")
        self.action_tool_start = QtWidgets.QAction(MainWindow)
        self.action_tool_start.setObjectName("action_tool_start")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.action_tool_chooseMainTrack = QtWidgets.QAction(MainWindow)
        self.action_tool_chooseMainTrack.setObjectName("action_tool_chooseMainTrack")
        self.action_tool_linkPort = QtWidgets.QAction(MainWindow)
        self.action_tool_linkPort.setObjectName("action_tool_linkPort")
        self.action_menu_export = QtWidgets.QAction(MainWindow)
        self.action_menu_export.setObjectName("action_menu_export")
        self.action_tool_correctToolFace = QtWidgets.QAction(MainWindow)
        self.action_tool_correctToolFace.setObjectName("action_tool_correctToolFace")
        self.action_tool_changeToolFace = QtWidgets.QAction(MainWindow)
        self.action_tool_changeToolFace.setObjectName("action_tool_changeToolFace")
        self.menu_2.addAction(self.action_menu_newProject)
        self.menu_2.addAction(self.action_menu_openProjiect)
        self.menu_2.addAction(self.action_menu_recentProject)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.action_menu_export)
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu3D.menuAction())
        self.toolBar.addAction(self.action_tool_chooseMainTrack)
        self.toolBar.addAction(self.action_tool_linkPort)
        self.toolBar.addAction(self.action_tool_start)
        self.toolBar.addAction(self.action_tool_correctToolFace)
        self.toolBar.addAction(self.action_tool_changeToolFace)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DrillTrack3D"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_image), _translate("MainWindow", "测斜轨迹"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_tabel), _translate("MainWindow", "测斜数据"))
        self.menu3D.setTitle(_translate("MainWindow", "设置"))
        self.menu_2.setTitle(_translate("MainWindow", "文件"))
        self.menu_3.setTitle(_translate("MainWindow", "显示"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Page 1"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Page 2"))
        self.action_menu_openProjiect.setText(_translate("MainWindow", "打开钻场"))
        self.action_menu_openProjiect.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.action_menu_newProject.setText(_translate("MainWindow", "新建钻场"))
        self.action_menu_newProject.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.action_menu_recentProject.setText(_translate("MainWindow", "最近打开的钻场"))
        self.action_tool_start.setText(_translate("MainWindow", "开始测量"))
        self.action_tool_start.setShortcut(_translate("MainWindow", "Ctrl+Alt+S"))
        self.action_6.setText(_translate("MainWindow", "停止测量"))
        self.action_tool_chooseMainTrack.setText(_translate("MainWindow", "选择主孔"))
        self.action_tool_chooseMainTrack.setShortcut(_translate("MainWindow", "Ctrl+Alt+C"))
        self.action_tool_linkPort.setText(_translate("MainWindow", "端口连接"))
        self.action_tool_linkPort.setShortcut(_translate("MainWindow", "Ctrl+Alt+P"))
        self.action_menu_export.setText(_translate("MainWindow", "导出"))
        self.action_menu_export.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.action_tool_correctToolFace.setText(_translate("MainWindow", "修正工具面"))
        self.action_tool_changeToolFace.setText(_translate("MainWindow", "调整工具面"))

from myWidget import myGLWidget_withGride, myPlotWidget_x, myPlotWidget_y, trackTree
