# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newRootTrack.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_newRootTrack(object):
    def setupUi(self, Dialog_newRootTrack):
        Dialog_newRootTrack.setObjectName("Dialog_newRootTrack")
        Dialog_newRootTrack.resize(409, 220)
        Dialog_newRootTrack.setMaximumSize(QtCore.QSize(410, 220))
        self.line = QtWidgets.QFrame(Dialog_newRootTrack)
        self.line.setGeometry(QtCore.QRect(20, 0, 16, 261))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Dialog_newRootTrack)
        self.line_2.setGeometry(QtCore.QRect(10, 10, 381, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.widget = QtWidgets.QWidget(Dialog_newRootTrack)
        self.widget.setGeometry(QtCore.QRect(40, 30, 351, 163))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.doubleSpinBox_dipAngle = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_dipAngle.setDecimals(1)
        self.doubleSpinBox_dipAngle.setMinimum(-90.0)
        self.doubleSpinBox_dipAngle.setMaximum(90.0)
        self.doubleSpinBox_dipAngle.setObjectName("doubleSpinBox_dipAngle")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_dipAngle)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.doubleSpinBox_intensity = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_intensity.setDecimals(1)
        self.doubleSpinBox_intensity.setMinimum(0.0)
        self.doubleSpinBox_intensity.setMaximum(99.0)
        self.doubleSpinBox_intensity.setObjectName("doubleSpinBox_intensity")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_intensity)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.lineEdit_RootTrackName = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_RootTrackName.setObjectName("lineEdit_RootTrackName")
        self.horizontalLayout.addWidget(self.lineEdit_RootTrackName)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.spinBox_designOrientation = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_designOrientation.setMaximum(360)
        self.spinBox_designOrientation.setObjectName("spinBox_designOrientation")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_designOrientation)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.spinBox_angle = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_angle.setMinimum(-30)
        self.spinBox_angle.setMaximum(30)
        self.spinBox_angle.setObjectName("spinBox_angle")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox_angle)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.spinBox_orientation = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_orientation.setMaximum(360)
        self.spinBox_orientation.setObjectName("spinBox_orientation")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBox_orientation)
        self.horizontalLayout_4.addWidget(self.groupBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_OK = QtWidgets.QPushButton(self.widget)
        self.pushButton_OK.setObjectName("pushButton_OK")
        self.horizontalLayout_2.addWidget(self.pushButton_OK)
        self.pushButton_Cancel = QtWidgets.QPushButton(self.widget)
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.horizontalLayout_2.addWidget(self.pushButton_Cancel)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Dialog_newRootTrack)
        QtCore.QMetaObject.connectSlotsByName(Dialog_newRootTrack)

    def retranslateUi(self, Dialog_newRootTrack):
        _translate = QtCore.QCoreApplication.translate
        Dialog_newRootTrack.setWindowTitle(_translate("Dialog_newRootTrack", "新建主孔"))
        self.groupBox_2.setTitle(_translate("Dialog_newRootTrack", "辅助参数"))
        self.label.setText(_translate("Dialog_newRootTrack", "地磁偏角"))
        self.doubleSpinBox_dipAngle.setSuffix(_translate("Dialog_newRootTrack", "°"))
        self.label_2.setText(_translate("Dialog_newRootTrack", "磁场强度"))
        self.doubleSpinBox_intensity.setSuffix(_translate("Dialog_newRootTrack", "μT"))
        self.label_6.setText(_translate("Dialog_newRootTrack", "主孔名："))
        self.groupBox.setTitle(_translate("Dialog_newRootTrack", "开孔参数"))
        self.label_3.setText(_translate("Dialog_newRootTrack", "设计方向"))
        self.spinBox_designOrientation.setSuffix(_translate("Dialog_newRootTrack", "°"))
        self.label_4.setText(_translate("Dialog_newRootTrack", "开孔倾角"))
        self.spinBox_angle.setSuffix(_translate("Dialog_newRootTrack", "°"))
        self.label_5.setText(_translate("Dialog_newRootTrack", "开孔方向"))
        self.spinBox_orientation.setSuffix(_translate("Dialog_newRootTrack", "°"))
        self.pushButton_OK.setText(_translate("Dialog_newRootTrack", "确认"))
        self.pushButton_Cancel.setText(_translate("Dialog_newRootTrack", "取消"))

