# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'statusBarWidget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 45)
        Form.setMaximumSize(QtCore.QSize(800, 45))
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.line_5 = QtWidgets.QFrame(Form)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_6.addWidget(self.line_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.label_magneticAngle = QtWidgets.QLabel(Form)
        self.label_magneticAngle.setText("")
        self.label_magneticAngle.setObjectName("label_magneticAngle")
        self.horizontalLayout_4.addWidget(self.label_magneticAngle)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        self.line_4 = QtWidgets.QFrame(Form)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_6.addWidget(self.line_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.label_magneticIntensity = QtWidgets.QLabel(Form)
        self.label_magneticIntensity.setText("")
        self.label_magneticIntensity.setObjectName("label_magneticIntensity")
        self.horizontalLayout_5.addWidget(self.label_magneticIntensity)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_6.addWidget(self.line_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.label_designDir = QtWidgets.QLabel(Form)
        self.label_designDir.setText("")
        self.label_designDir.setObjectName("label_designDir")
        self.horizontalLayout_3.addWidget(self.label_designDir)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_3)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_6.addWidget(self.line_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.label_dirAngle = QtWidgets.QLabel(Form)
        self.label_dirAngle.setText("")
        self.label_dirAngle.setObjectName("label_dirAngle")
        self.horizontalLayout_2.addWidget(self.label_dirAngle)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_6.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_dipAngle = QtWidgets.QLabel(Form)
        self.label_dipAngle.setText("")
        self.label_dipAngle.setObjectName("label_dipAngle")
        self.horizontalLayout.addWidget(self.label_dipAngle)
        self.horizontalLayout_6.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_7.setText(_translate("Form", "磁偏角："))
        self.label_9.setText(_translate("Form", "磁场强度："))
        self.label_5.setText(_translate("Form", "主设计方位："))
        self.label_3.setText(_translate("Form", "开孔方位角："))
        self.label.setText(_translate("Form", "开孔倾角："))

